### ISSUE TITLE
1.0 TODO

### ISSUE THREAD

**Issue by dfcreative** [dfcreative/regl-line2d#1]
* [x] `precision` property
* [x] duplicated point case
* [x] demo with randomized line
* [x] calibrated dash pattern
* [x] optimize shader code
* [x] readme and stuff
