### ISSUE TITLE
Feature-complete release

### ISSUE THREAD

**Issue by dfcreative** [dfcreative/regl-line2d#16]
* [ ] Round miters mode with proper normals, antialiasing #5 
* [ ] Avoid miterJoin crease for thick lines #15 
* [ ] Close path mode #11 
* [ ] Distance dash pattern mode #13 
* [ ] Rectangular mode with detection #4 
* [ ] Demo with updated settings panel
